CREATE PROC FI_SP_PesqBeneficiario
	@ID BIGINT
AS
BEGIN
	IF(ISNULL(@ID,0) = 0)
		SELECT b.ID, b.CPF, b.NOME, b.IDCLIENTE FROM BENEFICIARIOS b INNER JOIN CLIENTES c WITH(NOLOCK) on b.IDCLIENTE = c.ID where c.ID = @ID
	ELSE
		SELECT b.ID, b.CPF, b.NOME, b.IDCLIENTE FROM BENEFICIARIOS b INNER JOIN CLIENTES c WITH(NOLOCK) on b.IDCLIENTE = c.ID where c.ID = @ID
END