CREATE PROC FI_SP_AltBeneficiario
	@CPF           VARCHAR(14),
    @NOME          VARCHAR (50)
AS
BEGIN
	UPDATE BENEFICIARIOS 
	SET 
		NOME = @NOME
	WHERE ID = (SELECT ID FROM BENEFICIARIOS WHERE CPF = @CPF)
END